css: |
  .mordor-section banner {
     margin-top: 30px;
     margin-left: 30px;
     margin-right: 30px;
     border-radius: 10px;
  }
  .mordor-section banner-text-overlay {
     margin: 30px;
     padding: 20px;
  }
  .mordor-section banner-text {
     padding: 50px;
     color: #ffffff;
  }
  .mordor-section title {
     color: #ffffff;
  }
  .mordor-section subtitle {
    color: #ffffff;
    font-weight: 400;
  }
  .mordor-section {
    margin: 15px;
    border-radius: 25px;
  }

sections:
  - title: "Favorite Apps"
    subtitle: "Use these, they are great!"
    rows: 4
    # use the file:// prefix for a local file
    banner: file:///usr/share/mordor/backgrounds/ublue.png
    # can be "fill", "contain", "cover", or "scale-down"
    banner-fit: cover
    appids:
      - app.zen_browser.zen
      - com.google.Chrome
      - com.microsoft.Edge
      - com.discordapp.Discord
      - im.riot.Riot
      - com.slack.Slack
      - org.signal.Signal
      - tv.plex.PlexDesktop
      - com.spotify.Client
      - org.videolan.VLC
      - org.audacityteam.Audacity
      - org.gimp.GIMP
      - org.inkscape.Inkscape
      - org.libreoffice.LibreOffice
      - sh.ppy.osu
    classes:
      - mordor-section
